### ISSUE TITLE
getCurrentTestName shows wrong description

### ISSUE THREAD

**Issue by erwindemoel** [Jezorko/smack-my-jasmine-up#6]
Hi, I tried to implement your solution because we want to console.log the name of each running test within the fit(''). Here is my example code:

`  fit('testing my description', () => {
    console.log(JasmineSmacker.getCurrentTestName());
  });`

After following your steps, I do get a console.log with the name of one of our tests, however it is the wrong one. It logs the name of another test instead of the current one. How can I fix this so it logs the correct one?

**Comment by Jezorko** [comment]
Hey @erwindemoel, thanks for reporting this!
I've pushed a fix and will merge once the CI finishes (:
https://github.com/Jezorko/smack-my-jasmine-up/pull/10

**Comment by Jezorko** [comment]
The change is here: https://github.com/Jezorko/smack-my-jasmine-up/blob/c94c6ed1f727d259b5697a6fb74fff52899a1a0c/src/main/JasmineSmacker.js#L6-L9

To get this thing working, I am globally replacing the `it` function. Now both `it` and `fit` are replaced.

**Comment by Jezorko** [comment]
Also I see that the discussion under the issue has been updated with a [much nicer solution](https://github.com/jasmine/jasmine/issues/611#issuecomment-553098129).
